name: liferary
description: Google Developer Student Clubs 23 _ liferary
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_heatmap_calendar: ^1.0.5
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  intl: ^0.18.0
  rive: ^0.10.1
  fluttertoast: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.png